{
 "title": "1-dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Endpoint Availability",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "probe_success{job=\"blackbox\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Rate (req/sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    { "expr": "rate(http_requests_total[5m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Container CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{\r\n  name=~\"flask-app|prometheus|grafana|elasticsearch\"\r\n}[5m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Error Rate (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{status_code=~\"5..\"}[5m]))\r\n/\r\nsum(rate(http_requests_total[5m]))\r\n* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host Memory Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    { "expr": "http_active_requests", "legendFormat": "__auto" }
   ]
  }
 ]
}